import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://lab-03764-bos.lab.pega.com/prweb/app/tell-us-more-refrence/beEBp4uRVTogorRwSwWqbOtn9IL2fwdI*/!STANDARD?pzuiactionrrr=CXtpbn16MENndDZJTFBLbXBqNzVNWEtTUXIxdjBrMUhYTWtxRjJHTi9nWUxHaWtHd1RkTHlkUGFYcGFvU1JYV1hWdmhQUWZoWmlra1YzcHo0ODRPRkhUVDE4Zz09*');
  await page.getByPlaceholder('User name').click();
  await page.getByPlaceholder('User name').fill('');
  await page.getByPlaceholder('User name').click();
  await page.getByPlaceholder('User name').fill('CustomerREF@SL');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('password');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId(':privacy-dialog:accept').click();
  await page.getByRole('button', { name: 'Incident' }).click();
  await page.getByTestId('DetermineTypeDropdown:select:control').selectOption('Product faulty or unsafe');
  await page.getByTestId('DetermineSubtypeDropdown:select:control').selectOption('Product not as described');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByTestId('Name:input:control').click();
  await page.getByTestId('Name:input:control').fill('Mix');
  await page.getByTestId('field-block__column-count-3').getByTestId('Cost:currency-input:control').click();
  await page.getByTestId('field-block__column-count-3').getByTestId('Cost:currency-input:control').fill('$68');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByText('Name - Cookie Cream').click();
  await page.getByTestId('Name:input:control').dblclick();
  await page.getByTestId('Name:input:control').fill('Cookie Cream');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByTestId('field-block__column-count-3').getByTestId('Cost:currency-input:control').click();
  await page.getByTestId('field-block__column-count-3').getByTestId('Cost:currency-input:control').press('Insert');
  await page.getByTestId('field-block__column-count-3').getByTestId('Cost:currency-input:control').fill('$');
  await page.getByTestId('Name:input:control').click();
  await page.getByTestId('Name:input:control').fill('Mix');
  await page.getByTestId('field-block__column-count-3').click();
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByTestId(':fullscreen:').getByTestId(':form-field:label').locator('div').click();
  await page.getByRole('textbox', { name: 'Cost *" / "' }).click();
  await page.getByRole('textbox', { name: 'Cost *" / "' }).fill('$123');
  await page.getByTestId('What happened?:text-area:control').click();
  await page.getByTestId('What happened?:text-area:control').fill('sdfsdfsd');
  await page.getByTestId('Where did this happened?:text-area:control').click();
  await page.getByTestId('Where did this happened?:text-area:control').fill('sfsdfsdf');
  await page.getByTestId(':date-input:open-close-picker').click();
  await page.getByLabel('January 9,').click();
  await page.getByTestId(':date-input:open-close-picker').click();
  await page.getByTestId(':date-input::date-picker:calendar').getByLabel('January 9,').click();
  await page.getByTestId(':date-input:open-close-picker').click();
  await page.getByLabel('January 24,').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByTestId('First Name:input:control').click();
  await page.getByTestId('First Name:input:control').fill('ksdsdfsdf');
  await page.getByTestId('Last Name:input:control').click();
  await page.getByTestId('Last Name:input:control').fill('sdfsdfsdf');
  await page.getByTestId('Last Name:input:control').press('Tab');
  await page.getByTestId('E-Mail:input:control').fill('sadasd@o2.pl');
  await page.getByTestId('Phone Number:phone-input:country-code').selectOption('+48');
  await page.getByTestId('Phone Number:phone-input:control').click();
  await page.getByTestId('Phone Number:phone-input:control').fill('34 544 555');
  await page.locator('div:nth-child(2) > .sc-kSGOQU').click();
  await page.getByTestId('Postal Code:input:').locator('div').filter({ hasText: 'Postal Code' }).click();
  await page.getByTestId('Phone Number:phone-input:control').click();
  await page.getByTestId('Phone Number:phone-input:control').click();
  await page.getByTestId('Phone Number:phone-input:control').fill('37 77');
  await page.getByTestId('Phone Number:phone-input:control').click();
  await page.getByTestId('Phone Number:phone-input:control').fill('37777567567');
  await page.getByTestId('Phone Number:phone-input:control').click();
  await page.getByTestId('City:input:control').click();
  await page.getByTestId('City:input:control').fill('ghghj');
  await page.getByTestId('Street:input:control').click();
  await page.getByTestId('Street:input:control').fill('ghj45');
  await page.getByTestId('Postal Code:input:control').click();
  await page.getByTestId('Postal Code:input:control').fill('4456');
  await page.getByTestId('Country:select:control').selectOption('Azerbaijan');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByTestId('Phone Number:phone-input:control').click();
  await page.getByTestId('Phone Number:phone-input:control').fill('37777567567345');
  await page.getByTestId('Phone Number:phone-input:control').dblclick();
  await page.getByTestId('Phone Number:phone-input:control').fill('34 554 53 45');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByTestId('What would you like Sweet Life Inc  to do to resolve your issue?:select:control').selectOption('Gift');
  await page.getByTestId('What would you like Sweet Life Inc  to do to resolve your issue?:select:control').selectOption('Refund');
  await page.getByRole('button', { name: 'Next' }).click();
});